In [179]:
import pandas as pd

### customer_df

In [180]:
customer_df = pd.read_csv('../../data/raw/customers.csv')
customer_df.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

In [181]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1371980 non-null  str
 1   FN                      476930 non-null   float64
 2   Active                  464404 non-null   float64
 3   club_member_status      1365918 non-null  str
 4   fashion_news_frequency  1355969 non-null  str
 5   age                     1356119 non-null  float64
 6   postal_code             1371980 non-null  str
dtypes: float64(3), str(4)
memory usage: 73.3 MB

In [182]:
customer_df.describe()

             FN    Active           age
count  476930.0  464404.0  1.356119e+06
mean        1.0       1.0  3.638696e+01
std         0.0       0.0  1.431363e+01
min         1.0       1.0  1.600000e+01
25%         1.0       1.0  2.400000e+01
50%         1.0       1.0  3.200000e+01
75%         1.0       1.0  4.900000e+01
max         1.0       1.0  9.900000e+01

In [183]:
# Active의 결측치 = 906576 개
customer_df['Active'].isna().sum()

np.int64(907576)

In [184]:
# 총 activate의 수 = 464404 개
customer_df['Active'].notna().sum()

np.int64(464404)

In [185]:
# 전체 수  1371980개
len(customer_df)

1371980

In [186]:
customer_df['FN'].notna().sum()  # 뉴스 프로모션 수신 여부(구독 여부)

np.int64(476930)

In [187]:
customer_df.drop(columns=['postal_code','age',], inplace=True) # inplace는 원본 데이터프레임을 수정하는 옵션.
# True로 설정하면 원본 데이터프레임에서 해당 열이 삭제.
# False로 설정하면 삭제된 열이 포함된 새로운 데이터프레임이 반환.

In [188]:
customer_df.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly

In [189]:
customer_df['fashion_news_frequency'].isna().sum()  # 뉴스 프로모션 수신 빈도

np.int64(16011)

In [190]:
customer_df['fashion_news_frequency'].unique()

<StringArray>
['NONE', 'Regularly', nan, 'Monthly']
Length: 4, dtype: str

In [191]:
customer_df[customer_df['fashion_news_frequency'] != 'NONE'].count()

customer_id               494269
FN                        476141
Active                    463905
club_member_status        491912
fashion_news_frequency    478258
dtype: int64

In [192]:
temp_customer_df = customer_df[customer_df['fashion_news_frequency'] != 'NONE'] # NONE값들은 제거
temp_customer_df.describe()

             FN    Active
count  476141.0  463905.0
mean        1.0       1.0
std         0.0       0.0
min         1.0       1.0
25%         1.0       1.0
50%         1.0       1.0
75%         1.0       1.0
max         1.0       1.0

In [193]:
final_customer_df = temp_customer_df.dropna(inplace=False)

In [194]:
final_customer_df.info()

<class 'pandas.DataFrame'>
Index: 463592 entries, 4 to 1371978
Data columns (total 5 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   customer_id             463592 non-null  str
 1   FN                      463592 non-null  float64
 2   Active                  463592 non-null  float64
 3   club_member_status      463592 non-null  str
 4   fashion_news_frequency  463592 non-null  str
dtypes: float64(2), str(3)
memory usage: 21.2 MB

In [195]:
final_customer_df.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly
7,00007d2de826758b65a93dd24ce629ed66842531df6699...,1.0,1.0,ACTIVE,Regularly
13,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,1.0,1.0,ACTIVE,Regularly
14,0000ae1bbb25e04bdc7e35f718e852adfb3fbb72ef38b3...,1.0,1.0,ACTIVE,Regularly
15,0000b2f1829e23b24feec422ef13df3ccedaedc85368e6...,1.0,1.0,ACTIVE,Regularly

In [196]:
final_customer_df['fashion_news_frequency'].unique()

<StringArray>
['Regularly', 'Monthly']
Length: 2, dtype: str

In [197]:
final_customer_df.isna().sum()  # 결측치 확인

customer_id               0
FN                        0
Active                    0
club_member_status        0
fashion_news_frequency    0
dtype: int64

In [221]:
print(final_customer_df['FN'].value_counts().head(50))

FN
1.0    463592
Name: count, dtype: int64

---

### transaction_df

In [198]:
trasaction_df = pd.read_csv('../../data/raw/transactions_train.csv')
trasaction_df.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2

In [199]:
trasaction_df['sales_channel_id'].unique()

array([2, 1])

In [200]:
final_transction_df = trasaction_df.drop(columns=['price'], inplace=False)

In [201]:
final_transction_df.head()

,t_dat,customer_id,article_id,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,2

In [202]:
final_transction_df.isna().sum()  # 결측치 확인

t_dat               0
customer_id         0
article_id          0
sales_channel_id    0
dtype: int64

---

### articles_df

In [203]:
articles_df = pd.read_csv('../../data/raw/articles.csv')
articles_df.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

In [204]:
final_articles_df = articles_df.drop(columns=['graphical_appearance_no','graphical_appearance_name','colour_group_code','colour_group_name','product_type_no'
                          ,'product_type_name','department_no','department_name','index_code','index_name','index_group_no','index_group_name'
                          ,'product_group_name','perceived_colour_value_id','perceived_colour_value_name','perceived_colour_master_id','perceived_colour_master_name',
                          'section_name','detail_desc','garment_group_name','garment_group_no',], inplace=False)

In [205]:
final_articles_df.head()

   article_id  product_code          prod_name  section_no
0   108775015        108775          Strap top          16
1   108775044        108775          Strap top          16
2   108775051        108775      Strap top (1)          16
3   110065001        110065  OP T-shirt (Idro)          61
4   110065002        110065  OP T-shirt (Idro)          61

In [206]:
final_articles_df.isna().sum()  # 결측치 확인

article_id      0
product_code    0
prod_name       0
section_no      0
dtype: int64

---

# 위 모든 데이터 결측치 제거 확인

### join 하는 절차

- final_customer_df
- final_transction_df
- final_articles_df

- **customer_id**: 고객을 구분하는 고유 ID (조인 키)
- **FN**: 패션 뉴스/마케팅 정보 수신(또는 관심/동의) 여부
- **Active**: 최근 활동(구매/방문 등) 여부
- **club_member_status**: 클럽/멤버십 가입 상태 
- **fashion_news_frequency**: 패션 뉴스/마케팅 메시지 수신 빈도

In [212]:
final_customer_df.head(15)

,customer_id,FN,Active,club_member_status,fashion_news_frequency
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly
7,00007d2de826758b65a93dd24ce629ed66842531df6699...,1.0,1.0,ACTIVE,Regularly
13,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,1.0,1.0,ACTIVE,Regularly
14,0000ae1bbb25e04bdc7e35f718e852adfb3fbb72ef38b3...,1.0,1.0,ACTIVE,Regularly
15,0000b2f1829e23b24feec422ef13df3ccedaedc85368e6...,1.0,1.0,ACTIVE,Regularly
17,0000b95f630aaa9313028ce9c41154bb95ac7afa34f55b...,1.0,1.0,ACTIVE,Regularly
19,0000d6c053fc8f9389d4565051f12402d5774aa4a9d2e5...,1.0,1.0,ACTIVE,Regularly
20,0000e9a4db2da4e9c68558ad1e7df570d02767b213ec6b...,1.0,1.0,ACTIVE,Regularly
21,0000f1c71aafe5963c3d195cf273f7bfd50bbf17761c91...,1.0,1.0,ACTIVE,Regularly
25,000114c6996ef5703a8d455faf2103f8488d3928348e07...,1.0,1.0,PRE-CREATE,Regularly
26,0001177027259b455f979d85a278e4b280205d4de5cce4...,1.0,1.0,ACTIVE,Regularly
31,00018385675844f7a6babbed41b5655b5727fb16483b6e...,1.0,1.0,ACTIVE,Regularly
36,0001b0127d3e5ff8dadcfc6e5043682dba2070f2667081...,1.0,1.0,ACTIVE,Regularly
38,0001d44dbe7f6c4b35200abdb052c77a87596fe1bdcc37...,1.0,1.0,ACTIVE,Regularly
46,000253f6914890557a88d0b91288ce85fae9332dac43ee...,1.0,1.0,ACTIVE,Regularly

In [208]:
final_transction_df.head()

,t_dat,customer_id,article_id,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,2

In [214]:
final_transction_df['t_dat'] = pd.to_datetime(final_transction_df['t_dat'])

In [215]:
cust_feat = final_transction_df.groupby('customer_id').agg(
    n_tx=('t_dat', 'size'),             # 총 구매 횟수(거래 건수)
    last_purchase=('t_dat', 'max'),     # 마지막 구매일
    first_purchase=('t_dat', 'min'),    # 첫 구매일
    n_items=('article_id', 'nunique')   # 구매한 서로 다른 상품 수
).reset_index()

In [217]:
customer_merged_df = final_transction_df.merge(
    cust_feat, 
    on='customer_id',
    how='left'
)

In [ ]:
# gpt...
customer_merged_df['n_tx'] = customer_merged_df['n_tx'].fillna(0)
customer_merged_df['n_items'] = customer_merged_df['n_items'].fillna(0)

In [220]:
customer_df.head(20) # customer_id 기준으로 해서 FN , Active에 결측치가 생성

,customer_id,FN,Active,club_member_status,fashion_news_frequency
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly
5,000064249685c11552da43ef22a5030f35a147f723d5b0...,NaN,NaN,NaN,NaN
6,0000757967448a6cb83efb3ea7a3fb9d418ac7adf2379d...,NaN,NaN,ACTIVE,NONE
7,00007d2de826758b65a93dd24ce629ed66842531df6699...,1.0,1.0,ACTIVE,Regularly
8,00007e8d4e54114b5b2a9b51586325a8d0fa74ea23ef77...,NaN,NaN,ACTIVE,NONE
9,00008469a21b50b3d147c97135e25b4201a8c58997f787...,NaN,NaN,ACTIVE,NONE
10,0000945f66de1a11d9447609b8b41b1bc987ba185a5496...,NaN,NaN,ACTIVE,NONE
11,000097d91384a0c14893c09ed047a963c4fc6a5c021044...,NaN,NaN,ACTIVE,NONE
12,00009c2aeae8761f738e4f937d9be6b49861a66339c2b1...,NaN,NaN,ACTIVE,NONE
13,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,1.0,1.0,ACTIVE,Regularly
14,0000ae1bbb25e04bdc7e35f718e852adfb3fbb72ef38b3...,1.0,1.0,ACTIVE,Regularly
15,0000b2f1829e23b24feec422ef13df3ccedaedc85368e6...,1.0,1.0,ACTIVE,Regularly
16,0000b7a134c3ec0d8842fad1fd4ca28517424c14fc4848...,NaN,NaN,ACTIVE,NONE
17,0000b95f630aaa9313028ce9c41154bb95ac7afa34f55b...,1.0,1.0,ACTIVE,Regularly
18,0000c97821eb48d0e590fd309133f0a6c08f7750f64ccc...,NaN,NaN,ACTIVE,NONE
19,0000d6c053fc8f9389d4565051f12402d5774aa4a9d2e5...,1.0,1.0,ACTIVE,Regularly

### final_articles_df는 필요 없을 것 같은데 각자 생각해보고 피드백 해주세요

In [ ]:
final_articles_df.head() # 이건 굳이 필요할까?? EDA를 하기는 했는데 할 필요가 없어 보임
# 그렇게 생각한 이유 : 위에 merge한 걸로 충분히 고객 이탈을 충분히 예측 할 수 있을 것 같음

   article_id  product_code          prod_name  section_no
0   108775015        108775          Strap top          16
1   108775044        108775          Strap top          16
2   108775051        108775      Strap top (1)          16
3   110065001        110065  OP T-shirt (Idro)          61
4   110065002        110065  OP T-shirt (Idro)          61